name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and test on Ubuntu 18.04
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    # install packages
    - name: Install packages
      run: |
        sudo apt-get install freeglut3-dev libxi-dev libxmu-dev liblapack-dev
        sudo apt-get install doxygen swig python-dev cmake

    # setup dependencies
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v1
      with:
        path: ~/dependencies
        key: ${{ runner.os }}-dependencies-${{ hashFiles('dependencies/*') }}

    # setup OpenSim
    - name: Setup opensim-core
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        mkdir ~/dependencies
        wget https://sourceforge.net/projects/dependencies/files/opensim-core/opensim-core-4.1-ubuntu-18.04.tar.xz
        tar -xvf opensim-core-4.1-ubuntu-18.04.tar.xz -C ~/dependencies

    # setup OSCPack
    - name: Setup OSCPack
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        wget https://sourceforge.net/projects/dependencies/files/oscpack/oscpack-ubuntu-18.04.tar.xz
        tar -xvf oscpack-ubuntu-18.04.tar.xz -C ~/dependencies

    # setup ViconDataStreamSDK
    - name: Setup ViconDataStreamSDK
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        wget https://sourceforge.net/projects/dependencies/files/vicon/ViconDataStreamSDK_1.7.1_96542h.tar.xz
        tar -xvf ViconDataStreamSDK_1.7.1_96542h.tar.xz -C ~/dependencies

    # build and test
    - name: Build and test
      run: |
        export OPENSIM_HOME=~/dependencies/opensim-core
        export OpenSim_DIR=$OPENSIM_HOME/lib/cmake/OpenSim
        export PATH=$OPENSIM_HOME/bin:$PATH
        export LD_LIBRARY_PATH=$OPENSIM_HOME/lib:$LD_LIBRARY_PATH
        export OSCPACK_DIR=~/dependencies/oscpack
        export LD_LIBRARY_PATH=$OSCPACK_DIR/lib:$LD_LIBRARY_PATH
        export VICONDATASTREAM_DIR=~/dependencies/ViconDataStreamSDK_1.7.1_96542h/Linux64-boost-1.58.0/20170125_96542h.x64
        export LD_LIBRARY_PATH=$VICONDATASTREAM_DIR:$LD_LIBRARY_PATH
        mkdir build
        cd build
        cmake ../
            -DCMAKE_BUILD_TYPE:STRING=Release
            -DCMAKE_INSTALL_PREFIX:PATH=../install
            -DOpenSim_DIR:PATH=$OpenSim_DIR
            -DCONTINUOUS_INTEGRATION=ON
            -DBUILD_TESTING=ON
            -DBUILD_DOCUMENTATION=ON
            -DDOXYGEN_USE_MATHJAX=ON
            -DBUILD_MOMENT_ARM=ON
            -DBUILD_IMU=ON
            -DBUILD_VICON=OFF
            -DCMAKE_PREFIX_PATH=$OpenSim_DIR:$OSCPACK_DIR/lib:$VICONDATASTREAM_DIR
        make -j8
        ctest
        make install
